// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR8kVYGLWVwGz0beX9ocBk-AsSM2ixFO0',
    appId: '1:246295623015:web:9544fc2e435ecc428b6bc2',
    messagingSenderId: '246295623015',
    projectId: 'matrixtasktrackerdb',
    authDomain: 'matrixtasktrackerdb.firebaseapp.com',
    storageBucket: 'matrixtasktrackerdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8XhyBeAnXJfQo02W71tiDx9spcgi8_c',
    appId: '1:246295623015:android:d266f29d2e5ae6548b6bc2',
    messagingSenderId: '246295623015',
    projectId: 'matrixtasktrackerdb',
    storageBucket: 'matrixtasktrackerdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvCUKnbz8z98vBugTaekVF5QJz8lmY10',
    appId: '1:246295623015:ios:e88cc8eba33af07e8b6bc2',
    messagingSenderId: '246295623015',
    projectId: 'matrixtasktrackerdb',
    storageBucket: 'matrixtasktrackerdb.appspot.com',
    iosBundleId: 'com.example.matrixTaskTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYvCUKnbz8z98vBugTaekVF5QJz8lmY10',
    appId: '1:246295623015:ios:365155a15ae32ea38b6bc2',
    messagingSenderId: '246295623015',
    projectId: 'matrixtasktrackerdb',
    storageBucket: 'matrixtasktrackerdb.appspot.com',
    iosBundleId: 'com.example.matrixTaskTracker.RunnerTests',
  );
}
